### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by ylp1001** [dmm1005/GESPRO_PracticaGestionTareas_2021#3]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by erp1004** [comment]
![d292d962-e621-11e6-915a-a39387803ce0](https://user-images.githubusercontent.com/75205054/100541718-fa653100-3245-11eb-809e-bcb81c4bc673.png)

https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry
